# 1. 保留并修改原有配置
site_name: 六水合铬离子  # 改成你的网站名
site_url: https://LoshGreenz.github.io  

# 2. 保留主题配置
theme:
  name: material  # 核心主题，保留不动
  language: zh
  custom_dir: overrides
  # 未来可以在这里添加更多主题定制，比如：
  # palette:
  #   primary: 'indigo' 
  # 在mkdocs.yml中添加以下内容
extra_css:
  - stylesheets/extra.css

# 3. 【新增】最重要的部分：定义网站导航栏菜单！
nav:
  - 主页: index.md  # 第一个菜单项，链接到首页
  # - 博客:  # 第二个菜单项是一个下拉菜单，名为“博客”
  #     - '我的第一篇文章': my-first-post.md  # 下拉菜单里的第一篇文章
      # 未来你可以继续在这里添加更多文章
      # - '第二篇文章': second-post.md
  - 日本旅行:  # 第二个菜单项是一个下拉菜单，名为“博客”
      - 记录篇: 
          - 去日本的路上: reminiscene/8_25_Flight.md
          - 大阪: reminiscene/8_26_Osaka.md
          - 京都: reminiscene/8_27_Kyoto.md
          - 奈良&宇治: reminiscene/8_28_Nara.md
          - 东京: reminiscene/8_29_Tokyo.md
          - 东京&川崎: reminiscene/8_30_Kawasaki.md 
          - 箱根&江之岛: reminiscene/8_31_Hakone.md 
          - 名古屋: reminiscene/9_1_Nagoya.md  
      - 攻略篇: strategy.md        
  
  - 关于我: about.md  # 第三个菜单项，链接到一个“关于我”的页面

# 4. 【可选但推荐】添加一些插件来增强功能
plugins:
  - search  # 启用搜索功能，Material主题默认自带，写上更保险

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde