# 1. 保留并修改原有配置
site_name: 六水合铬离子  
site_url: https://www.loshgreenz.cn/
site_dir: site

# 2. 保留主题配置
theme:
  name: material  
  language: zh
  custom_dir: overrides
  favicon: image/favicon.ico
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css


nav:
  - 主页: index.md  
  - 日本旅行: 
      - 记录篇: 
          - 去日本的路上: reminiscene/8_25_Flight.md
          - 大阪: reminiscene/8_26_Osaka.md
          - 京都: reminiscene/8_27_Kyoto.md
          - 奈良&宇治: reminiscene/8_28_Nara.md
          - 东京: reminiscene/8_29_Tokyo.md
          - 东京&川崎: reminiscene/8_30_Kawasaki.md 
          - 箱根&江之岛: reminiscene/8_31_Hakone.md 
          - 名古屋: reminiscene/9_1_Nagoya.md  
      - 攻略篇: strategy.md        
  
  - 关于我: about.md  

plugins:
  - search  
  - glightbox
  - document-dates:
      show_author: false



markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde




  